name: tractian_mobile_challenge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

scripts:
  get: fvm flutter pub get
  clean:
    $script: fvm flutter clean
    $after: rps get
  gen:
    $script: dart run build_runner watch --delete-conflicting-outputs
  clean-gen:
    $before: rps clean
    $script: rps gen
  test:
    $before: fvm flutter pub run full_coverage
    $script: fvm flutter test --coverage

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  device_preview: ^1.2.0
  mobx: ^2.3.3+2
  equatable: ^2.0.5
  fpdart: ^1.1.0
  mobx_codegen: ^2.6.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/app_icon/

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/K2D-Light.ttf
          weight: 300
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 400
        - asset: assets/fonts/K2D-Regular.ttf
          weight: 500
        - asset: assets/fonts/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/K2D-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon_square.png"
  min_sdk_android: 21
  remove_alpha_ios: true